name: Deploy and robot tests in production

on:
  workflow_dispatch:
  push:
    branches:
      - rc-*

concurrency:
  group: uses-test-cognito-users
  cancel-in-progress: false

jobs:
  prod_robot_tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install packages
        run: yarn
      - name: Pre-deploy mobile-ui
        env:
          VITE_AWS_REGION: ${{ vars.VITE_AWS_REGION }}
          VITE_AWS_COGNITO_USER_POOL_ID: ${{ vars.VITE_AWS_COGNITO_USER_POOL_ID }}
          VITE_AWS_COGNITO_CLIENT_ID: ${{ vars.VITE_AWS_COGNITO_CLIENT_ID }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: yarn workspace mobile-ui pre-deploy

      - name: Install surge
        run: yarn global add surge

      - name: Surge deploy
        env:
          BASE_URL: http://diory-mobile-proto.surge.sh
          SURGE_DEPLOY_TOKEN: ${{ secrets.SURGE_DEPLOY_TOKEN }}
        run: surge ./apps/mobile-ui/dist --domain http://diory-mobile-proto.surge.sh --token $SURGE_DEPLOY_TOKEN

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git subtree split --prefix apps/mobile-server -b heroku-deploy
          git checkout heroku-deploy
          git push heroku heroku-deploy:main --force
          git checkout -- .
          git checkout -

          # Should work like this simple:
          # git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          # git subtree push --prefix apps/mobile-server heroku main

      - name: Toggle web process on in Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku ps:scale web=1 --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Robot Framework dependencies
        run: |
          pip install robotframework robotframework-browser
          rfbrowser init

      - name: Verify Python and Robot installation
        run: echo $(robot --version)

      - name: Wait for deploy to be applied
        run: sleep 3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_COGNITO_CLEANUP_ASSUME_ROLE }}
          aws-region: ${{ vars.VITE_AWS_REGION }}

      - name: Run Cognito cleanup
        env:
          USER_POOL_ID: ${{ vars.VITE_AWS_COGNITO_USER_POOL_ID }}
        run: ./scripts/cleanup-cognito-users.sh

      - name: Run Robot Framework tests
        env:
          BASE_URL: http://diory-mobile-proto.surge.sh
          AUTO_USER_EMAIL: ${{ vars.AUTO_USER_EMAIL }}
          NON_CONFIRMED_EMAIL: ${{ vars.NON_CONFIRMED_EMAIL}}
          EXISTING_EMAIL: ${{ vars.EXISTING_EMAIL }}
        run: robot tests/main.robot

      - name: Run Cognito cleanup
        env:
          USER_POOL_ID: ${{ vars.VITE_AWS_COGNITO_USER_POOL_ID }}
        run: ./scripts/cleanup-cognito-users.sh

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-outputs
          path: |
            /home/runner/work/mobile-proto/mobile-proto/output.xml
            /home/runner/work/mobile-proto/mobile-proto/log.html
            /home/runner/work/mobile-proto/mobile-proto/report.html
