name: Deploy and robot tests

on:
  workflow_dispatch:

jobs:
  prod_robot_tests:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install packages + pre-deploy
        env:
          VITE_AWS_REGION: ${{ vars.VITE_AWS_REGION }}
          VITE_AWS_COGNITO_USER_POOL_ID: ${{ vars.VITE_AWS_COGNITO_USER_POOL_ID }}
          VITE_AWS_COGNITO_CLIENT_ID: ${{ vars.VITE_AWS_COGNITO_CLIENT_ID }}
          VITE_CALLBACK_URL: ${{ vars.VITE_CALLBACK_URL }}
        run: yarn && yarn pre-deploy

      - name: Install surge
        run: yarn global add surge

      - name: Surge deploy
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          SURGE_DEPLOY_TOKEN: ${{ secrets.SURGE_DEPLOY_TOKEN }}
        run: surge ./dist --domain http://materialistic-insect.surge.sh --token $SURGE_DEPLOY_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Robot Framework dependencies
        run: |
          pip install robotframework robotframework-browser
          rfbrowser init

      - name: Verify Python and Robot installation
        run: echo $(robot --version)

      - name: Wait for deploy to be applied
        run: sleep 5

      - name: Run Robot Framework tests
        env:
          BASE_URL: http://materialistic-insect.surge.sh
          AUTO_USER_EMAIL: ${{ vars.AUTO_USER_EMAIL }}
          CONFIRMED_USER_EMAIL: ${{ vars.CONFIRMED_USER_EMAIL}}
          EXISTING_EMAIL: ${{ vars.EXISTING_EMAIL }}
        run: robot tests/main.robot

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-outputs
          path: |
            /home/runner/work/diograph-cli/diograph-cli/output.xml
            /home/runner/work/diograph-cli/diograph-cli/log.html
            /home/runner/work/diograph-cli/diograph-cli/report.html
