name: Lint & test

on:
  push:
    branches:
      - "*"
      - "!rc-*"

jobs:
  local_lint_test:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install
        run: yarn

      - name: Run mobile-server lint
        run: yarn workspace mobile-server lint

      - name: Run mobile-server tests
        run: yarn workspace mobile-server test

      - name: Run mobile-ui tests
        run: yarn workspace mobile-ui test
