name: Robot test in production

on: [push]

jobs:
  robot_framework_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Robot Framework dependencies
        run: |
          pip install robotframework robotframework-browser
          rfbrowser init

      - name: Verify Python and Robot installation
        run: echo $(robot --version)

      - name: Run Robot Framework tests
        env:
          FFMPEG_PATH: /usr/bin/ffmpeg
        run: robot tests/main.robot

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-outputs
          path: |
            /home/runner/work/diograph-cli/diograph-cli/output.xml
            /home/runner/work/diograph-cli/diograph-cli/log.html
            /home/runner/work/diograph-cli/diograph-cli/report.html
