name: Robot test

on:
  push:
    branches:
      - "*"
      - "!rc-*"

concurrency:
  group: uses-test-cognito-users
  cancel-in-progress: false

jobs:
  local_robot_tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Checkout demo-content-room
      #   uses: actions/checkout@v4
      #   with:
      #     path: "tests/demo-content-room"
      #     repository: "DioryMe/demo-content-room"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Robot Framework dependencies
        run: |
          pip install robotframework robotframework-browser
          rfbrowser init

      - name: Verify Python and Robot installation
        run: echo $(robot --version)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install
        run: yarn

      - name: Run server
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: yarn start:dev:all &

      - name: Wait for the frontend server to be ready
        run: |
          timeout 60 sh -c "until curl --silent --fail http://localhost:5173; do echo 'Waiting for server...'; sleep 1; done"

      - name: Wait for the backend server to be ready
        run: |
          timeout 60 sh -c "until curl --silent --fail http://localhost:3000/static-room/list; do echo 'Waiting for server...'; sleep 1; done"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_COGNITO_CLEANUP_ASSUME_ROLE }}
          aws-region: ${{ vars.VITE_AWS_REGION }}

      - name: Run Cognito cleanup
        env:
          USER_POOL_ID: ${{ vars.VITE_AWS_COGNITO_USER_POOL_ID }}
        run: ./scripts/cleanup-cognito-users.sh

      - name: Run Robot Framework tests
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          AUTO_USER_EMAIL: ${{ vars.AUTO_USER_EMAIL }}
          NON_CONFIRMED_EMAIL: ${{ vars.NON_CONFIRMED_EMAIL}}
          EXISTING_EMAIL: ${{ vars.EXISTING_EMAIL }}
        run: robot tests/main.robot

      - name: Run Cognito cleanup
        env:
          USER_POOL_ID: ${{ vars.VITE_AWS_COGNITO_USER_POOL_ID }}
        run: ./scripts/cleanup-cognito-users.sh

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-outputs
          path: |
            /home/runner/work/mobile-proto/mobile-proto/browser/screenshot/*
            /home/runner/work/mobile-proto/mobile-proto/output.xml
            /home/runner/work/mobile-proto/mobile-proto/log.html
            /home/runner/work/mobile-proto/mobile-proto/report.html
