name: Toggle web process on in Heroku

on:
  workflow_dispatch:
    inputs:
      toggle:
        description: "Scale dynos to..."
        required: true
        type: choice
        options:
          - 0:Basic (off)
          - 1:Basic (on)

jobs:
  toggle-web:
    runs-on: ubuntu-latest
    steps:
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Show version
        run: heroku --version
      - name: Toggle web process in Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          if [ "${{ github.event.inputs.toggle }}" == "1:Basic (on)" ]; then
            heroku ps:scale web=1 --app ${{ secrets.HEROKU_APP_NAME }}
          else
            heroku ps:scale web=0 --app ${{ secrets.HEROKU_APP_NAME }}
          fi
